// <auto-generated />
using System;
using System.Collections.Generic;
using Libreria.AccesoDatos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Libreria.AccesoDatos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260524213553_AgregueAuditoria")]
    partial class AgregueAuditoria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Libreria.LogicaNegocio.Entidades.Auditoria", b =>
                {
                    b.Property<int>("AuditoriaPrestamoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditoriaPrestamoId"));

                    b.Property<string>("Accion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrestamoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioCoordinadorId")
                        .HasColumnType("int");

                    b.HasKey("AuditoriaPrestamoId");

                    b.HasIndex("PrestamoId");

                    b.HasIndex("UsuarioCoordinadorId");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("Libreria.LogicaNegocio.Entidades.Equipo", b =>
                {
                    b.Property<int>("EquipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipoId"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("cantidadDisponible")
                        .HasColumnType("int");

                    b.Property<string>("marca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EquipoId");

                    b.ToTable("Equipos");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Equipo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Libreria.LogicaNegocio.Entidades.ObjetoCeleste", b =>
                {
                    b.Property<int>("ObjetoCelesteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObjetoCelesteId"));

                    b.Property<double>("magnitudAparente")
                        .HasColumnType("float");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("tipo")
                        .HasColumnType("int");

                    b.HasKey("ObjetoCelesteId");

                    b.ToTable("ObjetosCelestes");
                });

            modelBuilder.Entity("Libreria.LogicaNegocio.Entidades.ObservacionAstro", b =>
                {
                    b.Property<int>("ObservacionAstroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ObservacionAstroId"));

                    b.Property<int>("ObjetoCelesteId")
                        .HasColumnType("int");

                    b.Property<int>("PrestamoId")
                        .HasColumnType("int");

                    b.Property<string>("ResultadoIA")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("fechaObservacion")
                        .HasColumnType("datetime2");

                    b.HasKey("ObservacionAstroId");

                    b.HasIndex("ObjetoCelesteId");

                    b.HasIndex("PrestamoId");

                    b.ToTable("ObservacionAstros");
                });

            modelBuilder.Entity("Libreria.LogicaNegocio.Entidades.Prestamo", b =>
                {
                    b.Property<int>("PrestamoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrestamoId"));

                    b.Property<int?>("CamaraId")
                        .HasColumnType("int");

                    b.Property<int>("MonturaId")
                        .HasColumnType("int");

                    b.Property<int?>("OcularId")
                        .HasColumnType("int");

                    b.Property<int>("TelescopioId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("fechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fechaInicio")
                        .HasColumnType("datetime2");

                    b.HasKey("PrestamoId");

                    b.HasIndex("CamaraId");

                    b.HasIndex("MonturaId");

                    b.HasIndex("OcularId");

                    b.HasIndex("TelescopioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Prestamos");
                });

            modelBuilder.Entity("Libreria.LogicaNegocio.Entidades.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RolId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Libreria.LogicaNegocio.Entidades.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "NombreCompleto", "Libreria.LogicaNegocio.Entidades.Usuario.NombreCompleto#NombreCompletoVO", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Apellido")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Nombre")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");
                        });

                    b.HasKey("UsuarioId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Libreria.LogicaNegocio.Entidades.Camara", b =>
                {
                    b.HasBaseType("Libreria.LogicaNegocio.Entidades.Equipo");

                    b.Property<string>("resolucion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("tamañoPixel")
                        .HasColumnType("float");

                    b.Property<int>("tipoSensor")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Camara");
                });

            modelBuilder.Entity("Libreria.LogicaNegocio.Entidades.Montura", b =>
                {
                    b.HasBaseType("Libreria.LogicaNegocio.Entidades.Equipo");

                    b.Property<double>("cargaUtil")
                        .HasColumnType("float");

                    b.Property<bool>("esGoTo")
                        .HasColumnType("bit");

                    b.Property<string>("tipoMontura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Montura");
                });

            modelBuilder.Entity("Libreria.LogicaNegocio.Entidades.Ocular", b =>
                {
                    b.HasBaseType("Libreria.LogicaNegocio.Entidades.Equipo");

                    b.Property<double>("anguloVision")
                        .HasColumnType("float");

                    b.Property<double>("diametro")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("Ocular");
                });

            modelBuilder.Entity("Libreria.LogicaNegocio.Entidades.Telescopio", b =>
                {
                    b.HasBaseType("Libreria.LogicaNegocio.Entidades.Equipo");

                    b.Property<double>("apertura")
                        .HasColumnType("float");

                    b.Property<double>("distanciaFocal")
                        .HasColumnType("float");

                    b.Property<double>("peso")
                        .HasColumnType("float");

                    b.Property<string>("relacionFocal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Telescopio");
                });

            modelBuilder.Entity("Libreria.LogicaNegocio.Entidades.Auditoria", b =>
                {
                    b.HasOne("Libreria.LogicaNegocio.Entidades.Prestamo", "Prestamo")
                        .WithMany()
                        .HasForeignKey("PrestamoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Libreria.LogicaNegocio.Entidades.Usuario", "UsuarioCoordinador")
                        .WithMany()
                        .HasForeignKey("UsuarioCoordinadorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Prestamo");

                    b.Navigation("UsuarioCoordinador");
                });

            modelBuilder.Entity("Libreria.LogicaNegocio.Entidades.ObservacionAstro", b =>
                {
                    b.HasOne("Libreria.LogicaNegocio.Entidades.ObjetoCeleste", "ObjetoCeleste")
                        .WithMany()
                        .HasForeignKey("ObjetoCelesteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Libreria.LogicaNegocio.Entidades.Prestamo", "Prestamo")
                        .WithMany()
                        .HasForeignKey("PrestamoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObjetoCeleste");

                    b.Navigation("Prestamo");
                });

            modelBuilder.Entity("Libreria.LogicaNegocio.Entidades.Prestamo", b =>
                {
                    b.HasOne("Libreria.LogicaNegocio.Entidades.Camara", "Camara")
                        .WithMany()
                        .HasForeignKey("CamaraId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Libreria.LogicaNegocio.Entidades.Montura", "Montura")
                        .WithMany()
                        .HasForeignKey("MonturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Libreria.LogicaNegocio.Entidades.Ocular", "Ocular")
                        .WithMany()
                        .HasForeignKey("OcularId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Libreria.LogicaNegocio.Entidades.Telescopio", "Telescopio")
                        .WithMany()
                        .HasForeignKey("TelescopioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Libreria.LogicaNegocio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camara");

                    b.Navigation("Montura");

                    b.Navigation("Ocular");

                    b.Navigation("Telescopio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Libreria.LogicaNegocio.Entidades.Usuario", b =>
                {
                    b.HasOne("Libreria.LogicaNegocio.Entidades.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Libreria.LogicaNegocio.Entidades.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
